### ISSUE TITLE
IP Address

### ISSUE THREAD

**Issue by Talhazzers** [pterodactyl/whmcs#102]
Can the dedicatedip filled in the WHMCS service properties in the createaccount function
![npeOLl00PB9tOpIe](https://user-images.githubusercontent.com/57840480/137199652-8e9db9b2-82fa-4698-a795-36ceb793f0c9.png)
?

**Comment by Talhazzers** [comment]
I tested this code in 1.X but it is returning ":", IP and port is empty

**Comment by ConanDoyl** [comment]
Have you updated your API Permission? because you need the permission for the Allocations the module says it doesn't need it by default but this extension need it.

**Comment by Talhazzers** [comment]
Thanks, working.
