### ISSUE TITLE
Module Command Error

### ISSUE THREAD

**Issue by djiga88** [pterodactyl/whmcs#103]
Module Command Error
Failed to create the server, received the error code: 500. Enable module debug log for more info.

Array
(
[errors] => Array
(
[0] => Array
(
[code] => DaemonConnectionException
[status] => 500
[detail] => There was an error while communicating with the machine running this server. This error has been logged, please try again. (code: 500) (request_id: 6b9a8c73-ca51-414b-9c54-956e8cf2c407)
)

    )

[status_code] => 500
)

**Comment by TrixterTheTux** [comment]
Your daemon isn't accessible by the Pterodactyl panel hence the error, please use the [Pterodactyl Discord](https://discord.gg/pterodactyl) for configuration related support instead of GitHub issues.
