### ISSUE TITLE
oom_disabled not working

### ISSUE THREAD

**Issue by Talhazzers** [pterodactyl/whmcs#110]
OOM is always turned off on install. oom_disabled doesn't work.

**Comment by Software-Noob** [comment]
Show the value, and your module debug logs for the server creation request. It would be disabled on the panel by default unless you overwrite it to false

**Comment by Talhazzers** [comment]
`"oom_disabled":false,"` on module debug logs. OOM is not marked as disabled but when server is created OOM is disabled on server.

**Comment by Software-Noob** [comment]
Can you please share the module logs and the order template because I can't reproduce this

**Comment by TrixterTheTux** [comment]
This is due to the panel ignoring the option, which as far as I'm aware should be fixed in v2.
