### ISSUE TITLE
Autosetup assigns server to random user

### ISSUE THREAD

**Issue by tideodk** [pterodactyl/whmcs#111]
Hi!
Ever since the newest WHMCS update, im having issues where my installation will assign a new order to an already registered user.
Example:

user1@email.com is an active client.

user2@email.com orders new server

Module will setup server on user1@email.com´s account.

![image](https://user-images.githubusercontent.com/74503649/148545648-fe28f138-8dae-4393-ab2a-5502c3d7e0fd.png)

I am unsure on how to resolve this. I´ve tried repasting the new updated module to my WHMCS installation. 

Please let me know what debugging you need to look into this, and maybe someone else has issues. 

-----
If the random user it assigns the server has 0 servers, and I delete the user, and then recreate the server in whmcs - it Will assign the correct user

**Comment by TrixterTheTux** [comment]
The user has external_id set in Pterodactyl to the client's ID in WHMCS, thus the module assumes that the user was created before by the module itself. If you're using something that also sets user's external_id field then it'll conflict with this module and lead to this similar behavior.

**Comment by tideodk** [comment]
Hi.
I assume this field is not editable from the users tab, but rather from the database?

**Comment by tideodk** [comment]
> The user has external_id set in Pterodactyl to the client's ID in WHMCS, thus the module assumes that the user was created before by the module itself. If you're using something that also sets user's external_id field then it'll conflict with this module and lead to this similar behavior.

Would removing the creation of the user from the module remove the conflict?

**Comment by tideodk** [comment]
> The user has external_id set in Pterodactyl to the client's ID in WHMCS, thus the module assumes that the user was created before by the module itself. If you're using something that also sets user's external_id field then it'll conflict with this module and lead to this similar behavior.

Hi again. I just dug down into my database, and I see some users have WHMCS_User_token set, where others are null. I assume this is the cause of my issue, that these are not meant to be null. Is this correct assumed?

**Comment by tideodk** [comment]
Hi everyone!
I was using a modification that made my WHMCS create a Pterodactyl account anytime someone created a WHMCS account. In this case, some customers created WHMCS accounts to order other products, and the module always assume that the next external_id is the one that it created. Thus, it would just assign the server to the next external_id (which may not even be a client that is using pterodactyl, but rather a other product)

Thanks for all the help :-)
