### ISSUE TITLE
Set Username

### ISSUE THREAD

**Issue by alexbgameson** [pterodactyl/whmcs#39]
How can users set there username as opposed to WHMCS randomly generating one?

**Comment by TrixterTheTux** [comment]
Hi,

Currently this isn't possible out of the box, but you can modify the line https://github.com/pterodactyl/whmcs/blob/8783734bba56e9f1c30fd8c8030b0dced59b04e3/pterodactyl/pterodactyl.php#L276 to something like `'username' => pterodactyl_GetOption($params, 'username', pterodactyl_GenerateUsername()),` and setup a configurable option with the name "username". Though keep in mind that the deployment will fail if it conflicts with any existing usernames and will require manual intervention through the admin area for the service to deploy.
