### ISSUE TITLE
WHMCS - Max players

### ISSUE THREAD

**Issue by predator95** [pterodactyl/whmcs#42]
hi
i have a problem with this module.
you have a solution for max players option? i tried with "Players Slots', but don't work.
i need to make more modification in pterodactyl panel? for example to edit start command or other things.

this is from documentation:
This also works for any name of environment variable:
Player Slots => Will overwrite the environment variable named "Player Slots" to its value.

what i need to do for set max slot in whmcs?

thank you.

**Comment by VilhelmPrytz** [comment]
I think you have to use it like this:
```
player_slots|Player Slots
```

Then name your environment variable `player_slots`.

**Comment by TrixterTheTux** [comment]
Please use the [Pterodactyl Discord](https://discord.gg/pterodactyl) for configuration related support instead of GitHub issues.
