### ISSUE TITLE
Invalid status_code received: 401. Possible solutions: Authorization header either missing or not provided.

### ISSUE THREAD

**Issue by TyLinfoot** [pterodactyl/whmcs#44]
At the part where I insert the API key without a user, getting the error

> Invalid status_code received: 401. Possible solutions: Authorization header either missing or not provided.
Any ideas?

**Comment by TrixterTheTux** [comment]
Please use the [Pterodactyl Discord](https://discord.gg/pterodactyl) for configuration related support instead of GitHub issues.
