### ISSUE TITLE
Username not saved in whmcs

### ISSUE THREAD

**Issue by HostRK1** [pterodactyl/whmcs#45]
Hello,

Clients usernames aren't saved in whmcs, the field remains blank even after the product is activated (created): [![Screenshot from Gyazo](https://gyazo.com/aba1c557aaadbc08ca3010eb3e68e781/raw)](https://gyazo.com/aba1c557aaadbc08ca3010eb3e68e781)
The creation process works well, the user and server get created and that information is sent back to whmcs, but not saved: [![Screenshot from Gyazo](https://gyazo.com/3dfbf4219654659c03d540671a10ff82/raw)](https://gyazo.com/3dfbf4219654659c03d540671a10ff82)

It seems like the module isn't saving the username as any other whmcs module and as in the tutorial video: https://www.youtube.com/watch?v=wURpRD9vfj4 (minute 13:18)

I need the username to be saved so I can send welcome mails automaticaly using whmcs....without the username whmcs isn't able to send the username to the customer...

WHMCS version: 7.7.1
PHP version: 5.6.4

**Comment by TrixterTheTux** [comment]
Hi,

There is no way for me to track the username as the user can change it at any time making the WHMCS' data outdated. The client's email works fine instead of the username, and ptero sends an email with their username + link to setup their password.
