### ISSUE TITLE
Wrong password shown in whmcs 

### ISSUE THREAD

**Issue by HostRK1** [pterodactyl/whmcs#46]
The password shown in the whmcs admin area is always wrong: (for example this [![Screenshot from Gyazo](https://gyazo.com/432b7007cd5eadce1c4d24e118602134/raw)](https://gyazo.com/432b7007cd5eadce1c4d24e118602134) )
I am not sure this is an issue or it is ment to be like that for security reasons.
This makes imposible to send welcome mails using whmcs, could you somehow add the option to generate and save the first generated password there and then whmcs can send it via welcome mail ? Or to send the user that setup password link...
This would make mail tracking much more easy and combined with the change password option we could help users to change the password (and get that password via email) much more easily... I know this makes it less secure, but almost all provisoning server modules do the same thing (cPanel, multicraft, Plesk, Gamecp, etc..)
Also I know that pterodactyl sends some emails already, but if you add this feature to the whmcs module, it would be much easier for us to create custom emails with server details, product details and payment details (all in one mail), as we used to do this with multicraft. This is very usefull when dealing with malicios users tring to refund via paypal even you gave them the server details.... (I know from my experience that the WHMCS welcome mail is a very good proof of digital product delivery and paypal accepts it).

**Comment by TrixterTheTux** [comment]
Same issue as in https://github.com/pterodactyl/whmcs/issues/23#issuecomment-426589097
And even ignoring the security issue this introduces, I can't know the user's password if the account already exists => not able to send the actual password making the whole idea of this useless.
