### ISSUE TITLE
Keep getting 422 error code.

### ISSUE THREAD

**Issue by Connorcivi** [pterodactyl/whmcs#47]
Hello,

I have followed everything you said on your installation guide. So I tested by buying a minecraft server off my panel and I enabled debug logger so I can see errors so I did buy it and this error came up: 

Array
(
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => required
                    [detail] => The Server Jar File variable field is required.
                    [source] => Array
                        (
                            [field] => environment.SERVER_JARFILE
                        )

                )

            [1] => Array
                (
                    [code] => required
                    [detail] => The Build Number variable field is required.
                    [source] => Array
                        (
                            [field] => environment.BUILD_NUMBER
                        )

                )

        )

    [status_code] => 422
)

Build is set to default on my panel and server jar file is server.jar?

Any answers would help me!

Thanks - Connorcivi

**Comment by TrixterTheTux** [comment]
Please use the [Pterodactyl Discord](https://discord.gg/pterodactyl) for configuration related support instead of GitHub issues.
