### ISSUE TITLE
variables

### ISSUE THREAD

**Issue by superboys2017** [pterodactyl/whmcs#48]
this addon variable wil not work wen i use {memory}

**Comment by TrixterTheTux** [comment]
You're gonna have to provide a lot more info. Where are you putting this? What is the result? What were you expecting?

**Comment by superboys2017** [comment]
![image](https://user-images.githubusercontent.com/40305210/77482907-3b8b8280-6e27-11ea-8887-dea67b444aa2.png)
![image](https://user-images.githubusercontent.com/40305210/77482931-480fdb00-6e27-11ea-9a3a-2aa49ab021a9.png)
i make a custom cart page an i wil let show the memory and ssd from the package

**Comment by superboys2017** [comment]
can i user pterodacty packege installinge to my custom template @TrixterTheTux

**Comment by TrixterTheTux** [comment]
All the module does is allow provisioning Pterodactyl servers. If your custom template requires modifications to the module's code you're welcome to implement them as the code is open source. Though it isn't the module's job to inject these variables into the template (as how would it get them?) and doing what you want should be possible in some other way, but that isn't related to the module and just general theme development for WHMCS.
