### ISSUE TITLE
Typing the word "dot" instead of just putting a period

### ISSUE THREAD

**Issue by RoottheAdmin** [pterodactyl/whmcs#50]
![image](https://user-images.githubusercontent.com/43898535/78452706-5abdb780-7652-11ea-96b4-fb4256224ec6.png)

**Comment by RoottheAdmin** [comment]
It typed out the word dot instead of putting .

**Comment by TrixterTheTux** [comment]
Hi,
There's no such feature in the first place for this to be the cause of the module. There's no reproduction steps for this and from everyone who've used this module has never reported this that leads me to think it's an issue caused by your setup and not the module.
