### ISSUE TITLE
WHMCS Password not getting passed to Pterodactyl

### ISSUE THREAD

**Issue by AndyDevy** [pterodactyl/whmcs#51]
Hello there!

While troubleshooting with a colleague, I noticed the Add-On doesn't really pass the password generated by WHMCS onto the Pterodactyl panel. We fixed this by simply adding this line:

```php
'password' => $params['password']
```

to the following code block:

```php
if($userResult['meta']['pagination']['total'] === 0) {
                $userResult = pterodactyl_API($params, 'users', [
                    'username' => pterodactyl_GetOption($params, 'username', pterodactyl_GenerateUsername()),
                    'email' => $params['clientsdetails']['email'],
                    'first_name' => $params['clientsdetails']['firstname'],
                    'last_name' => $params['clientsdetails']['lastname'],
                    'external_id' => $params['clientsdetails']['id'],
                    // Added the line here
                ], 'POST');
            }
```

Now, this seemed like a very easy and trivial fix to a very complex situation, so I'd like to know if this isn't already featured in the source code because of a security issue or if it was simply a mistake.

Best regards, keep up the awesome work ^^.

**Comment by parkervcp** [comment]
Please fill out the information when you submit an issue. With no information on what versions you are running then we cannot identify where the actual issue is.

I will be closing this out now.

**Comment by parkervcp** [comment]
Or I read this and thought it was for pterodactyl and not whmcs. I apologize.

**Comment by Lunaversitay** [comment]
You're not suppose to be-able to pass the password.

The user password in WHMCS is hashed & salted, and having it plain text transfer over to pterodactyl will be a massive security issue.

**Comment by mayed505** [comment]
@Lunaversitay From what I can tell, it is not the client's password. It's the per order password where it autogenerates a random one.
Regardless it is at best to leave the password to be made through Pterodactyl's "Setup your Account" page instead of having WHMCS create a random password.

**Comment by Sir3lit** [comment]
iirc, Pterodactyl sends the user an email when the account is created for user to create their own password.

**Comment by triptronics** [comment]
Here's the problem with this guys. We don't want to sit there and send the clients 20 emails before they can access their account. The client needs to be able to access all the data needed for their server in one email (one we can easily modify as needed). If we shouldn't be passing the password variable over... then how do we get the server to respond back with the link the client can use to create their password?

**Comment by triptronics** [comment]
In addition, if the data is encrpyted (as it should be when communicating with the Ptera API), why should this be a security risk passing the password over? Plenty of other modules pass the password over...

**Comment by Lunaversitay** [comment]
> 
> 
> iirc, Pterodactyl sends the user an email when the account is created for user to create their own password.

Yes, pterodactyl sends an email and the user sets up their account that way.



> 
> 
> In addition, if the data is encrpyted (as it should be when communicating with the Ptera API), why should this be a security risk passing the password over? Plenty of other modules pass the password over...

lol what app transfers a users' password to another app? I haven't heard of something like that because things like oauth exist. Also it doesn't send "20 emails" it sends 1 email for the client to setup their account on pterodactyl and that's the end of it.

**Comment by Sir3lit** [comment]
Isn't it just best to allow the user to set their own password in the first place? As I'm sure 80% of people change their password from the randomly generated ones anyways. One less  stop by the end user.

**Comment by triptronics** [comment]
> > iirc, Pterodactyl sends the user an email when the account is created for user to create their own password.
> 
> Yes, pterodactyl sends an email and the user sets up their account that way.
> 
> > In addition, if the data is encrpyted (as it should be when communicating with the Ptera API), why should this be a security risk passing the password over? Plenty of other modules pass the password over...
> 
> lol what app transfers a users' password to another app? I haven't heard of something like that because things like oauth exist. Also it doesn't send "20 emails" it sends 1 email for the client to setup their account on pterodactyl and that's the end of it.
> (also side note: the passwords are not encrypted they're **hashed & salted** - two very different things)

Tell that to the people who developed the WHMCS CPanel and Virtualmin module lol. I don't disagree with the idea of having a link the user can click to change the password. We just feel like it could be implemented better. Maybe there is a way to include the link in the welcome email WHMCS sends? At the end of the day, we are going to integrate the panel with OpenID so the user has one set of login credentials for all the apps... just trying to see if there is something that could help those who aren't going to be using OpenID in the future.

**Comment by TrixterTheTux** [comment]
Hi,
This behavior is intentional.

The password and username fields are not used by the module because individual servers don't have a username or password. For the same reason changing password is also disabled.

Even if I had the username and password of the actual account, it would be useless as I don't have any way to track it e.g. if the user changes their username/password. This also would be a security risk as passwords shouldn't be stored in plaintext just to allow this.

Pterodactyl handles getting password to the customer and won't cause major confusion to the customer when he receives a password to his account that isn't valid (due to them already having an account before, leaving them with 2 different service passwords) or getting it changed just to have a valid password sent with the service activated email.

**Comment by Lunaversitay** [comment]
> 
> 
> > > iirc, Pterodactyl sends the user an email when the account is created for user to create their own password.
> > 
> > 
> > Yes, pterodactyl sends an email and the user sets up their account that way.
> > > In addition, if the data is encrpyted (as it should be when communicating with the Ptera API), why should this be a security risk passing the password over? Plenty of other modules pass the password over...
> > 
> > 
> > lol what app transfers a users' password to another app? I haven't heard of something like that because things like oauth exist. Also it doesn't send "20 emails" it sends 1 email for the client to setup their account on pterodactyl and that's the end of it.
> > (also side note: the passwords are not encrypted they're **hashed & salted** - two very different things)
> 
> Tell that to the people who developed the WHMCS CPanel and Virtualmin module lol. I don't disagree with the idea of having a link the user can click to change the password. We just feel like it could be implemented better. Maybe there is a way to include the link in the welcome email WHMCS sends? At the end of the day, we are going to integrate the panel with OpenID so the user has one set of login credentials for all the apps... just trying to see if there is something that could help those who aren't going to be using OpenID in the future.

None of those apps send passwords to another app? Implementing WHMCS SSO would require editing the pterodactyl panel, while it's 100% possible (you can check wisp.gg for example) I don't believe it'll be something natively added to Pterodactyl because they want to be as agnostic as possible.
I really don't see the problem either with having an email to setup the panel, you only get the email once and once your account is setup you never have to set it up again.

**Comment by triptronics** [comment]
> > > > iirc, Pterodactyl sends the user an email when the account is created for user to create their own password.
> > > 
> > > 
> > > Yes, pterodactyl sends an email and the user sets up their account that way.
> > > > In addition, if the data is encrpyted (as it should be when communicating with the Ptera API), why should this be a security risk passing the password over? Plenty of other modules pass the password over...
> > > 
> > > 
> > > lol what app transfers a users' password to another app? I haven't heard of something like that because things like oauth exist. Also it doesn't send "20 emails" it sends 1 email for the client to setup their account on pterodactyl and that's the end of it.
> > > (also side note: the passwords are not encrypted they're **hashed & salted** - two very different things)
> > 
> > 
> > Tell that to the people who developed the WHMCS CPanel and Virtualmin module lol. I don't disagree with the idea of having a link the user can click to change the password. We just feel like it could be implemented better. Maybe there is a way to include the link in the welcome email WHMCS sends? At the end of the day, we are going to integrate the panel with OpenID so the user has one set of login credentials for all the apps... just trying to see if there is something that could help those who aren't going to be using OpenID in the future.
> 
> None of those apps send passwords to another app? Implementing WHMCS SSO would require editing the pterodactyl panel, while it's 100% possible (you can check wisp.gg for example) I don't believe it'll be something natively added to Pterodactyl because they want to be as agnostic as possible.
> I really don't see the problem either with having an email to setup the panel, you only get the email once and once your account is setup you never have to set it up again.

If sending the passwords over is a security risk, then we will not do that. If it means the user has to read two emails for now, we are fine with that. One extra email shouldn't hurt :) Appreciate the time you guys took to look over this. Thank you!
