### ISSUE TITLE
Invalid status_code received: 500

### ISSUE THREAD

**Issue by DominicSpencerHartman** [pterodactyl/whmcs#53]
When I go WHMCS and add a Pterodactyl server I get (Invalid status_code received: 500. Possible solutions: Panel errored, check panel logs.). Here is the log file [https://bin.ptdl.co/lsu6v/](url)

**Comment by TrixterTheTux** [comment]
Please use the [Pterodactyl Discord](https://discord.gg/pterodactyl) for configuration related support instead of GitHub issues.

**Comment by DominicSpencerHartman** [comment]
ok thanks
