### ISSUE TITLE
Filesystem Error

### ISSUE THREAD

**Issue by HaloFloof** [pterodactyl/whmcs#55]
Hey, I am trying to install the WHMCS module, but I cannot add the server. It gives this error in the panel logs: ```[2020-07-19 14:17:52] production.ERROR: ErrorException: file_put_contents(/var/www/pterodactyl/storage/framework/cache/data/54/7e/547e8233c20e047bc2a38d4c6cf8621b8ce3c49c): failed to open stream: No such file or directory in /var/www/pterodactyl/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122```. I also checked, and this file indeed does not exist. I'm not sure what is causing the problem. Please do help. **Thank you!** 😄

**Comment by TrixterTheTux** [comment]
Please use the [Pterodactyl Discord](https://discord.gg/pterodactyl) for configuration related support instead of GitHub issues.

**Comment by HaloFloof** [comment]
@TrixterTheTux I did they don't know what the issue is.

**Comment by TrixterTheTux** [comment]
As what username?

**Comment by HaloFloof** [comment]
Dev.Not

**Comment by HaloFloof** [comment]
And I was trying to figure this out for the past few days now

**Comment by HaloFloof** [comment]
I am thinking its maybe a bug in the module

**Comment by TrixterTheTux** [comment]
The error has nothing to do with the module.

**Comment by HaloFloof** [comment]
And they just banned me for no reason -_- they are a really frustrating team
