### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by JorisCarmiggelt** [pterodactyl/whmcs#60]
Invalid status_code received: 0. Possible solutions: Check module debug log for more detailed error.
I get that when adding the server.

![image](https://user-images.githubusercontent.com/59412957/88380650-37f01400-cda5-11ea-9492-89ee0b03fd10.png)

**Comment by TrixterTheTux** [comment]
Please use the [Pterodactyl Discord](https://discord.gg/pterodactyl) for configuration related support instead of GitHub issues.
