### ISSUE TITLE
Custom Server Version Selection

### ISSUE THREAD

**Issue by Aidan-Warner** [pterodactyl/whmcs#61]
While the majority of the server options are available to be picked by the customer using custom fields, there doesn't seem to be a way to offer the option for customers to choose their preferred server version.

**Comment by parkervcp** [comment]
Is this not what variables are for?

**Comment by Aidan-Warner** [comment]
From testing, no environment variables have worked.  Any chance you could explain how I would go about this?

**Comment by parkervcp** [comment]
You would need a custom image and a start script that uses the variable if you want them to be able to change versions on start.

**Comment by TrixterTheTux** [comment]
This is already possible with [overwriting the variables/egg_id](https://github.com/pterodactyl/whmcs#overwriting-values-through-configurable-options) the server deploys with as mentioned above. Configuration issues should also go to the Pterodactyl Discord mentioned in the README over GitHub issues.
