### ISSUE TITLE
Cryptic error in WHMCS (sometimes) when creating users in pterodactyl

### ISSUE THREAD

**Issue by paz** [pterodactyl/whmcs#63]
``Failed to create user, received error code: 0. Enable module debug log for more info.``
In the module log, I can't actually find any errors. Code 201 for the post - https://[panel]/api/application/users

This error only occassionally shows up, but it prevents the server from being created. Retrying it from the module log results in a success however. 

I'd appreciate any further steps I should take to diagnose this issue.

**Comment by TrixterTheTux** [comment]
The error code 0 can be caused by any networking issue, you'd need to have the module debug logs enabled beforehands for it to be able to log the issue.

**Comment by paz** [comment]
I think it might be my ratelimit settings in nginx being weird then.. I'll try a few things and see if I can fix it or atleast get some better logs.
