### ISSUE TITLE
Changing Username and Password does not work

### ISSUE THREAD

**Issue by Nickolas00** [pterodactyl/whmcs#64]
Hello,

Each time i want to change the username or password from Admin panel -> Module Commands -> Change Password
got this:
**The password cannot be empty.**

Well never mind i try to debug it by comment this line
`/* if($params['password'] === '') throw new Exception('The password cannot be empty.'); */`

and add this:
```
// Debug
throw new Exception('Username result: ' .$params['username']. '| Password result: ' .$params['password']);

Returns:
Username result = empty
Password result = empty
```
Thank you.

**Comment by TrixterTheTux** [comment]
You need to save the username/password before clicking the change password button - this is how WHMCS works and not an issue with the module.

**Comment by Nickolas00** [comment]
> 
> 
> You need to save the username/password before clicking the change password button - this is how WHMCS works and not an issue with the module.

Ok, i am not so advanced in coding sorry for misunderstood.
How i can save it before clicking the button?

Thanks
