### ISSUE TITLE
the Steam Account Token variable field is required

### ISSUE THREAD

**Issue by csgo-s** [pterodactyl/whmcs#68]
I can not create a csgo server 
required [detail] => The Steam Account Token variable field is required.
In which field should I enter the token?

**Comment by TrixterTheTux** [comment]
Please use the [Pterodactyl Discord](https://discord.gg/pterodactyl) for configuration related support instead of GitHub issues.

**Comment by csgo-s** [comment]
No one is accountable there...

**Comment by Dancbeunny98** [comment]
up

**Comment by username-98** [comment]
up

**Comment by username-98** [comment]
when i select csgo server, panel replies "The Steam Account Token variable field is required." and there is no such field to put data on it

**Comment by TrixterTheTux** [comment]
Refer to my first reply here.
