### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by zapz12** [pterodactyl/whmcs#73]
Option to assign existing servers to user

**Comment by AreYouRlyScared** [comment]
Are you talking about changing the owner of the server? If so that's been a thing for ages...

On the admin panel, click the server, and navigate over to details. then see below
![image](https://user-images.githubusercontent.com/1757840/95669746-c4fb6b80-0b51-11eb-9c71-1ec1bd4a3cb9.png)

**Comment by TrixterTheTux** [comment]
This can be already done by activating service in WHMCS and setting the server's external_id on Pterodactyl to the service id.
