### ISSUE TITLE
Invalid status_code received: 401.

### ISSUE THREAD

**Issue by Rhydium** [pterodactyl/whmcs#74]
WHMCS Version: v8.0.2
Pterodactyl version: Panel@1.0.1 / Wings@1.0

When trying to test the connection with the module I'm getting this error:
`Invalid status_code received: 401. Possible solutions: Authorization header either missing or not provided.`

I filled the API key in the password field and filled the hostname and IP address fields with the IP of the server that has the panel on it.

**Comment by TrixterTheTux** [comment]
Please use the [Pterodactyl Discord](https://discord.gg/pterodactyl) for configuration related support instead of GitHub issues.
