### ISSUE TITLE
Auto Start Orders in WHMCS

### ISSUE THREAD

**Issue by csgo-s** [pterodactyl/whmcs#80]
Hi
I might set the WHMCS setting wrong
every thing in our server is okay and game server creation is so soft and easy peasy lemon squeezy
but the ordered server does not start automatically after the order and it must be accepted manually,
**please show us a way to turn it to automatic way.**

Pterodactyl Panel version 1.2.0
Pterodactyl Wings version 1.2.0

**Comment by TrixterTheTux** [comment]
Autoaccepting orders aren't the responsibility of the module. All it does is relay events when WHMCS tells it to, so there's nothing that controls this.
