### ISSUE TITLE
Module Create Failed

### ISSUE THREAD

**Issue by skippybossx** [pterodactyl/whmcs#81]
Module Create Failed - Service ID: 3 - Error: Failed to create user, received error code: 403. Enable module debug log for more info.

In module debug all it says is:
Action:
get - https://panel.mydomainname.com/api/application/users/external/1
Request:
[]

**Comment by TrixterTheTux** [comment]
Please use the [Pterodactyl Discord](https://discord.gg/pterodactyl) for configuration related support instead of GitHub issues.
