### ISSUE TITLE
Weird Module behavior with WHMCS 8.x

### ISSUE THREAD

**Issue by Profited** [pterodactyl/whmcs#83]
Invoices and services that are marked as paid before the due date still get suspended/terminated without notice. Cron job does not tell the administrator if a service was terminated/suspended. 

Double checked the users subscription end time and also due dates, everything was due in a later date so there was no way the module should've ran.

**Comment by TrixterTheTux** [comment]
The module doesn't manage any of the subscriptions nor invoices/services related to it. All it does is make specific actions whenever WHMCS tells it to, so I highly doubt this is an issue with the module.
