### ISSUE TITLE
Save suspended gameserver on external data like hdd and move him back when the Server is unsuspended

### ISSUE THREAD

**Issue by Felix5566** [pterodactyl/whmcs#85]
Save suspended gameserver on external data like hdd and move him back when the Server is unsuspended:

When a game server is suspend mode, the server will go into copy mode.
In copy mode all data is copied from the game server to an external storage.
If the gameserver has been successfully moved to the external storage, the gameserver is deleted from the node and the reserved "Memory Allocated" and "Disk Space Allocated" is released again from the node.

If the player wants to have the server again, he has to pay the bill, so the server is unsuspended and the data is copied back.

**Comment by theMackabu** [comment]
sounds like there is alot of space for trouble, such as like, a file not copied right.

**Comment by danny6167** [comment]
So what happens when the customer pays the bill and the whole thing falls apart because you unreserved the HDD and RAM space and the node is now filled by other customers?
Lots of potential points of failure here without any real gain.

**Comment by DaneEveritt** [comment]
This is not something that this module alone can accomplish effectively, and per https://github.com/pterodactyl/panel/issues/3094 I'm not building that functionality into the core.
