### ISSUE TITLE
🚀 Feature Request: More then 1 Overwriting values through configurable options in one field

### ISSUE THREAD

**Issue by Felix5566** [pterodactyl/whmcs#88]
i want to offer gameserver for testing, because i don't want to create a testproduct for every game there must be the possibility in a field the nest_id and egg_id.

**For example:**
For Minecraft Paper: 
**nest_id|placeholder|egg_id|game**
          1|placeholder|3|Minecraft Paper

And this can also be addet at ram and storage:
For 1GB RAM and 2GB SSD Storage
**memory|placeholder|disk|RAM and SSD Storage**
            1|placeholder|2|1GB RAM : 2GB SSD

Only the last name will be displayed in the store and on the invoice.

Configurable Options: https://i.imgur.com/fQAT0Q7.png

Shop Site: https://i.imgur.com/T9Th8rL.png

**Comment by Software-Noob** [comment]
WHMCS configurable options can only overwrite one value. You create multiple different configurable options, instead of cramming them all into one
