### ISSUE TITLE
[Request] customization

### ISSUE THREAD

**Issue by githubAlireza** [pterodactyl/whmcs#91]
Please add building the server with user's own configurations, 
like this: https://marketplace.whmcs.com/product/2390-openstack-vps-cloud-for-whmcs

also add a feature to automatically edit customers' configs by editing in WHMCS client panel, for instance when adding 1 GB of RAM is needed.

**Comment by TrixterTheTux** [comment]
You can already allow customizable configuration with the module. Refer to the [readme](https://github.com/pterodactyl/whmcs#overwriting-values-through-configurable-options).
