### ISSUE TITLE
Clicking on the Product

### ISSUE THREAD

**Issue by Officalpvp123** [pterodactyl/whmcs#95]
Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

For additional assistance, please reference the WHMCS TroubleShooting Guide »

Laminas\HttpHandlerRunner\Exception\EmitterException: Unable to emit response; headers already sent in /home/botservi/public_html/vendor/laminas/laminas-httphandlerrunner/src/Exception/EmitterException.php:19
Stack trace:
#0 /home/botservi/public_html/vendor/laminas/laminas-httphandlerrunner/src/Emitter/SapiEmitterTrait.php(36): Laminas\HttpHandlerRunner\Exception\EmitterException::forHeadersSent()
#1 /home/botservi/public_html/vendor/laminas/laminas-httphandlerrunner/src/Emitter/SapiEmitter.php(27): Laminas\HttpHandlerRunner\Emitter\SapiEmitter->assertNoPreviousOutput()
#2 /home/botservi/public_html/clientarea.php(0): Laminas\HttpHandlerRunner\Emitter\SapiEmitter->emit(Object(WHMCS\ClientArea))
#3 {main}

**Comment by Software-Noob** [comment]
WHMCS breaking when viewing a product is not a module related issue. Contact WHMCS for assistance if you can't figure it out.
