### ISSUE TITLE
cant install FIVEM server with this module 

### ISSUE THREAD

**Issue by fightree** [pterodactyl/whmcs#96]
i tried selling FIVEM servers with this module but its not working. 
this is the error code :Failed to create the server, received the error code: 422. Enable module debug log for more info. 
i am already selling Minecraft and discord bot servers so I know something isn't working just with this FIVEM

**Comment by danny6167** [comment]
You didn't even follow the instructions to troubleshoot.
This isn't a problem with the module, you didn't set up the product right.
Selling FiveM servers is against the ToS and you won't receive any help to do so.

**Comment by parkervcp** [comment]
You cannot sell fivem servers unless you have an agreement with the fivem team.

We will not support the breaking of their TOS either way.
