### ISSUE TITLE
curl error - every time i try to accept order

### ISSUE THREAD

**Issue by fightree** [pterodactyl/whmcs#99]
I have a problem now when I try to accept an order it doesn't work . 
the error that it sows me is this : 
pterodactyl-whmcs    curl error Operation timed out after 5001 milliseconds with 0 bytes received
I have already a few clients and this is worked before but now this is not working.

**Comment by WaffleThief123** [comment]
Is there any more to the logs? Also is your pterodactyl panel and WHMCS running on the same machine?

**Comment by djiga88** [comment]
> Is there any more to the logs? Also is your pterodactyl panel and WHMCS running on the same machine?

yes

same errot

**Comment by TrixterTheTux** [comment]
Please use the [Pterodactyl Discord](https://discord.gg/pterodactyl) (#whmcs-module channel) for configuration related support instead of GitHub issues.
